# configs/presets_c.yaml
global:
  daggen_bin: "${VIRTUAL_ENV}/bin/daggen"
  graphs_per_subfolder: 100
  subfolders_per_tier: 10
  seed_base: 4242   # فقط برای نمونه‌گیری داخلی اسکریپت؛ به daggen پاس داده نمی‌شود.

tiers:
  1-easy:
    n: [10, 20]
    fat: [0.35, 0.50]
    density: [0.20, 0.40]
    regular: [0.60, 0.80]
    jump: [0.00, 0.10]     # مجاز به صفر تا 0.1
    compute:               # compute-heavy → نسبت محاسبه بالا، داده کمتر
      ccr: [0.25, 0.30]
      mindata: 262144      # 256KB
      maxdata: 2097152     # 2MB
    data:                  # data-heavy → نسبت انتقال بالاتر
      ccr: [0.30, 0.35]
      mindata: 1048576     # 1MB
      maxdata: 8388608     # 8MB

  2-normal:
    n: [20, 35]
    fat: [0.50, 0.70]
    density: [0.40, 0.60]
    regular: [0.40, 0.60]
    jump: [0.10, 0.20]
    compute:
      ccr: [0.35, 0.40]
      mindata: 524288      # 512KB
      maxdata: 8388608     # 8MB
    data:
      ccr: [0.40, 0.45]
      mindata: 2097152     # 2MB
      maxdata: 16777216    # 16MB

  3-complex:
    n: [35, 50]
    fat: [0.70, 0.88]
    density: [0.60, 0.80]
    regular: [0.20, 0.40]
    jump: [0.20, 0.35]
    compute:
      ccr: [0.45, 0.50]
      mindata: 1048576     # 1MB
      maxdata: 16777216    # 16MB
    data:
      ccr: [0.50, 0.55]
      mindata: 4194304     # 4MB
      maxdata: 33554432    # 32MB
